# Supabase project configuration.
#
# A project_id is required. It can be found in your project's URL:
# https://supabase.com/dashboard/project/<project_id>
#
# You can also use the --project-ref flag to specify the project id.

project_id = "fxpdfkianxufsjsblgpi"

[api]
# Port to use for the API proxy.
port = 54321
# Schemas to expose in your API.
schemas = ["public", "storage", "graphql"]
# Extra schemas to add to the search_path of roles.
extra_search_path = ["public"]
# Maximum number of rows to return from a view, table, or function.
max_rows = 1000

[db]
# Port to use for the local database.
port = 54322
# Use a major version number.
major_version = 15

[studio]
# Port to use for Supabase Studio.
port = 54323

# Email testing server.
[inbucket]
# Port to use for the email testing server.
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.sync-offers]
import_map = "./functions/import_map.json"
