
name = "rewardspeak"
compatibility_date = "2024-05-01"

[pages]
main = "./.vercel/output/static"

[build]
command = "npm run build"
watch_dir = "src"

[[routes]]
pattern = "/_next/static/*"
kind = "asset"
path = "/.next/static/*"
